Try to make it run

diff --git a/modules/cron-puppet/files/post-merge b/modules/cron-puppet/files/post-merge
--- a/modules/cron-puppet/files/post-merge
+++ b/modules/cron-puppet/files/post-merge
@@ -1,13 +1,13 @@
 #!/bin/bash -e
-## fire puppet
+## Run Puppet locally using puppet apply
 /usr/bin/puppet apply /etc/puppet/manifests/site.pp
 
-## log
-if [ $? -wq 0]
+## Log status of the Puppet run
+if [ $? -eq 0 ]
 then
-	/usr/bin/logger -i "Puppet has run successfully" -t "puppet-run"
-	exit 0
+    /usr/bin/logger -i "Puppet has run successfully" -t "puppet-run"
+    exit 0
 else
-	/usr/bin/logger -i "Puppet ran into error(s)" -t "puppet-run"
-	exit 1
+    /usr/bin/logger -i "Puppet has ran into an error, please run Puppet manually" -t "puppet-run"
+    exit 1
 fi
